// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzipeI9gDrC-YtyEgfO_uVuK_cb9aEZOM',
    appId: '1:752368020867:web:414237e0241e713820dab6',
    messagingSenderId: '752368020867',
    projectId: 'training-log-app-taki',
    authDomain: 'training-log-app-taki.firebaseapp.com',
    storageBucket: 'training-log-app-taki.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvqIIc-M_RjZYYDhfc37ZS4YZxS3La-V0',
    appId: '1:752368020867:android:1527e29ab906ad4020dab6',
    messagingSenderId: '752368020867',
    projectId: 'training-log-app-taki',
    storageBucket: 'training-log-app-taki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXSXZ83y4CCqvTYgmjLB6W-_9ApuHejiU',
    appId: '1:752368020867:ios:84d87a99af9b3aab20dab6',
    messagingSenderId: '752368020867',
    projectId: 'training-log-app-taki',
    storageBucket: 'training-log-app-taki.firebasestorage.app',
    iosBundleId: 'com.example.trainingLogApp',
  );
}
